chore: Added Gravestone game objects
ByteBuildersLabs/StarkHack2024FrontEndv2 pull request #146
Opened 2024-11-22 16:19 UTC by DanielEmmanuel1

Summary
- Duplicated gravestone gameobject
- Repositioned all duplicates accordingly

2024-11-22 16:25 UTC, DanielEmmanuel1 commented
@jimenezz22 All done
Please review

2024-11-24 22:07 UTC, jimenezz22 reviewed
Can you provide evidence of the changes you made and a detailed summary of what you did? I see you are not following our pull request template

2024-11-25 00:03 UTC, DanielEmmanuel1 commented
Changes i made
- I imported the reference image into unity
- Then I drop it as the first child of the Grid gameobject making sure it perfectly fits the grid
- Then I disabled the Ground object so I can see the reference image in the background
- Then I duplicated the Grave objects and positioned them over the graves in the reference image
- Then I deleted the reference image and set the re-enabled the Ground object
- Then I deleted the reference image from the project

@jimenezz22 I didn't read the readme indepthly, that was an oversight from my part and i do apologise for that, I just went through the readme and if need be, i can still create a branch, push from there and create a new PR, whatever works for u.

2024-11-26 10:55 UTC, jimenezz22 requested changes

2024-11-26 10:55 UTC, jimenezz22 commented on Assets/Scenes/DarkForest.unity
This looks like you removed the scene from the pr

2024-11-26 14:02 UTC, DanielEmmanuel1 commented on Assets/Scenes/DarkForest.unity
I'll handle this now

2024-11-26 14:28 UTC, DanielEmmanuel1 commented
Hi @jimenezz22 

I think the issue here is someone else made updates to the scene while I was making changes to it too
And now there's a conflict because as u know GitHub cannot merge Unity scenes.

A feasible solution will be to discard/revert my changes, then I'll pull and implement the changes again
But you have to let me know as soon as you have reverted the changes to avoid another scene conflict

Is this okay?

2024-11-26 20:00 UTC, DanielEmmanuel1 commented
@jimenezz22 Please can u check now

2024-11-27 08:25 UTC, jimenezz22 approved these changes
pr already tested on my local repo and works successfully

2024-11-27 22:05 UTC, closed without merging